[package]
name = "example-sol-contract"
version = "0.2.0"
authors = ["Pyth Data Foundation"]
workspace = "../../"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
arrayref = "0.3.6"
borsh.workspace = true
solana-program.workspace = true
pyth-sdk-solana.workspace = true 
