[package]
name = "test-contract"
version = "0.2.2"
edition = "2018"

[features]
test-bpf = []
no-entrypoint = []

[dependencies]
pyth-sdk-solana = { path = "../", version = "0.6.1" }
solana-program = "1.14.3"
bytemuck = "1.7.2"
borsh = "0.9"
borsh-derive = "0.9.0"

[dev-dependencies]
solana-program-test = "1.14.3"
solana-client = "1.14.3"
solana-sdk = "1.14.3"

[lib]
crate-type = ["cdylib", "lib"]

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]
